-- MySQL Script generated by MySQL Workbench
-- Sat May 28 11:18:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema insta
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema insta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `insta` DEFAULT CHARACTER SET utf8 ;
USE `insta` ;

-- -----------------------------------------------------
-- Table `insta`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insta`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `user_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NULL,
  `mobile` VARCHAR(15) NULL,
  `birthdate` DATE NULL,
  `gender` ENUM('male', 'female') NULL,
  `created_at` DATETIME  DEFAULT current_timestamp,
  `update_at` DATETIME  DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) ,
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insta`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insta`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `body` VARCHAR(1000) NULL,
  `users_id` INT UNSIGNED NOT NULL,
  `category` ENUM('public', 'friends') NULL,
  `created_at` DATETIME NULL DEFAULT current_timestamp,
  `update_at` DATETIME NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_posts_users1_idx` (`users_id` ASC) ,
  CONSTRAINT `fk_posts_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `insta`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insta`.`post_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insta`.`post_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NULL,
  `post_id` INT NOT NULL,
  `created_at` DATETIME NULL DEFAULT current_timestamp,
  `update_at` DATETIME  NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `fk_post_images_posts_idx` (`post_id` ASC) ,
  CONSTRAINT `fk_post_images_posts`
    FOREIGN KEY (`post_id`)
    REFERENCES `insta`.`posts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insta`.`friendes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insta`.`friendes` (
  `users_id` INT UNSIGNED NOT NULL,
  `friend_id` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NULL DEFAULT current_timestamp,
  INDEX `fk_friendes_users1_idx` (`users_id` ASC) ,
  INDEX `fk_friendes_users2_idx` (`friend_id` ASC) ,
  PRIMARY KEY (`users_id`, `friend_id`),
  CONSTRAINT `fk_friendes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `insta`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_friendes_users2`
    FOREIGN KEY (`friend_id`)
    REFERENCES `insta`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insta`.`post_likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insta`.`post_likes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `type` ENUM('like', 'love', 'smile', 'angry') NULL,
  `created_at` DATETIME NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `fk_post_likes_posts1_idx` (`post_id` ASC) ,
  INDEX `fk_post_likes_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_post_likes_posts1`
    FOREIGN KEY (`post_id`)
    REFERENCES `insta`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_likes_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `insta`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `insta`.`post_comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `insta`.`post_comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(255) NULL,
  `created_at` DATETIME NULL DEFAULT current_timestamp,
  PRIMARY KEY (`id`),
  INDEX `fk_post_likes_posts1_idx` (`post_id` ASC) ,
  INDEX `fk_post_likes_users1_idx` (`user_id` ASC) ,
  CONSTRAINT `fk_post_likes_posts10`
    FOREIGN KEY (`post_id`)
    REFERENCES `insta`.`posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_likes_users10`
    FOREIGN KEY (`user_id`)
    REFERENCES `insta`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
